name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Define Variables
      run: |
        export REPO_NAME="$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//")"
        echo "::set-env name=RepositoryName::$REPO_NAME"
        
    - name: Setup Nuget.exe
      uses: nuget/setup-nuget@v1

    - name: Add Source
      run: |
        nuget source Add -Name "GitHub" -Source "https://nuget.pkg.github.com/KloderGit/index.json" -UserName KloderGit -Password ${{ secrets.GITHUB_TOKEN }}
        nuget restore -s "GitHub"
             
    - name: Build with dotnet
      run: dotnet build --configuration Release -o ./${{ env.RepositoryName }}/publish  
