name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        source-url: https://nuget.pkg.github.com/KloderGit/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1        
        
        
    - name: Define Variables
      run: |
        export REPO_NAME="$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//")"
        echo "::set-env name=RepositoryName::$REPO_NAME"
      
    - name: Build with dotnet
      run: dotnet publish --configuration Release -o ./${{ env.RepositoryName }}/publish  
