name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        source-url: https://nuget.pkg.github.com/KloderGit/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Define RepositoryName
      run: echo "::set-env name=RepositoryName::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//")"

    - name: Build with dotnet
      run: dotnet publish --configuration Release   

    - name: Define Version
      run: echo "::set-env name=AppVersion::$(monodis --assembly ./${{ env.RepositoryName }}/bin/Release/netcoreapp3.1/publish/${{ env.RepositoryName }}.dll | grep Version | sed 's/\s\+/,/g' | cut -d , -f2)"

    - name: Printenv
      run: printenv
      
    - name: Ls
      run: |
        ls
        echo '------------------------------'
        echo ${{ env.AppVersion }}
        echo "$GITHUB_ACTOR"
        echo ${{ env.RepositoryName }}
        echo $($GITHUB_ACTOR | tr "[:lower:]" "[:upper:]")
        echo "${$GITHUB_ACTOR,,}"

