name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        source-url: https://nuget.pkg.github.com/KloderGit/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
    - name: Build with dotnet
      run: dotnet publish --configuration Release -o ./${{ env.RepositoryName }}/publish

    - name: Define Repository Name
      run: |
        export REPO_NAME="$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//")"
        echo "::set-env name=RepositoryName::$REPO_NAME"
        echo "::set-env name=RepositoryNameLowcase::$(echo $REPO_NAME | tr '[:upper:]' '[:lower:]')"
        
    - name: Define Owner Name
      run: |        
        export GITHUB_ACTOR_LOWERCASE="$(echo $GITHUB_ACTOR | tr '[:upper:]' '[:lower:]')"
        echo "::set-env name=GitHubActorLowercase::$GITHUB_ACTOR_LOWERCASE"
        
#    - name: Define Project Name
#      run: |        
#        export PROJECT_NAME = $(basename $(echo $(find ./${{ env.RepositoryName }}/*.csproj)) .csproj )
#        echo "::set-env name=ProjectName::$PROJECT_NAME"

    - name: Define Application Version
      run: echo "::set-env name=AppVersion::$(monodis --assembly ./${{ env.RepositoryName }}/publish/${{ env.ProjectName }}.dll | grep Version | sed 's/\s\+/,/g' | cut -d , -f2)"

    - name: Ls
      run: |
        echo '------------------------------'
        echo ${{ env.RepositoryName }}
        echo ${{ env.RepositoryNameLowcase }}
        echo ${{ env.AppVersion }}
        echo "$GITHUB_ACTOR"
        echo ${{ env.GitHubActorLowercase }}
        echo basename $(echo $(find ./${{ env.RepositoryName }}/*.csproj)) .csproj

       
    - name: Docker Image
      run: docker image build -t ${{ env.RepositoryNameLowcase }} ./${{ env.RepositoryName }}
      
    - name: Docker Login
      run: docker login -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}} docker.pkg.github.com
      
    - name: Publish to Registry
      run: |
        docker tag ${{ env.RepositoryNameLowcase }} docker.pkg.github.com/${{ env.GitHubActorLowercase }}/${{ env.RepositoryNameLowcase }}/${{ env.RepositoryNameLowcase }}:dev
        docker push docker.pkg.github.com/${{ env.GitHubActorLowercase }}/${{ env.RepositoryNameLowcase }}/${{ env.RepositoryNameLowcase }}:dev        
        docker tag ${{ env.RepositoryNameLowcase }} docker.pkg.github.com/${{ env.GitHubActorLowercase }}/${{ env.RepositoryNameLowcase }}/${{ env.RepositoryNameLowcase }}:${{ env.AppVersion }}
        docker push docker.pkg.github.com/${{ env.GitHubActorLowercase }}/${{ env.RepositoryNameLowcase }}/${{ env.RepositoryNameLowcase }}:${{ env.AppVersion }}
