name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        source-url: https://nuget.pkg.github.com/KloderGit/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Build with dotnet
      run: dotnet publish --configuration Release -o publish
       
    - name: Cd
      run: cd GitHubBuildTest/bin/Release/netcoreapp3.1
        
    - name: Docker Image
      run: docker image build -t githubbuildtest:latest GitHubBuildTest/
      
    - name: Docker Push
      run: |
        docker login -u KloderGit -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
        docker push docker.pkg.github.com/KloderGit/GitHubBuildTest/githubbuildtest:latest
